### ISSUE TITLE
请求api报错

### ISSUE THREAD

**Issue by aichenxinyu** [ztgreat/react-authority#1]
可以提供下api数据么？运行项目请求api报错
![image](https://user-images.githubusercontent.com/14177686/54666635-39f8f180-4b25-11e9-9731-3c978042ea78.png)

**Comment by ztgreat** [comment]
> 可以提供下api数据么？运行项目请求api报错
> ![image](https://user-images.githubusercontent.com/14177686/54666635-39f8f180-4b25-11e9-9731-3c978042ea78.png)

这个需要后端的配合，不是mock 数据。
具体的项目，再readme里面有介绍

**Comment by ztgreat** [comment]
> 可以提供下api数据么？运行项目请求api报错
> ![image](https://user-images.githubusercontent.com/14177686/54666635-39f8f180-4b25-11e9-9731-3c978042ea78.png)

@aichen28 
这个需要后端的配合，不是mock 数据。
具体的项目，再readme里面有介绍

**Comment by ztgreat** [comment]
@aichen28 
这个需要后端的配合，不是mock 数据。
具体的项目，再readme里面有介绍
